// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: choices.sql

package store

import (
	"context"
)

const addChoice = `-- name: AddChoice :exec
INSERT INTO choices (fruits)
VALUES ($1)
`

func (q *Queries) AddChoice(ctx context.Context, fruits []Fruit) error {
	_, err := q.db.Exec(ctx, addChoice, fruits)
	return err
}
